# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: d2d0710
_src_path: .
author_email: hasansezertasan@gmail.com
author_full_name: Hasan Sezer Taşan
github_repo_name: example
github_user: hasansezertasan
short_description: A Python project example.
